DROP TABLE IF EXISTS safety_networks CASCADE;

CREATE TABLE safety_networks (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  sn_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);