DROP TABLE IF EXISTS locations ON CASCADE;

CREATE TABLE locations (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  address VARCHAR(255) NOT NULL,
  created_at DATE NOT NULL
);