insert into safety_networks (sn_id, user_id) values (1, 3);
insert into safety_networks (sn_id, user_id) values (2, 3);
insert into safety_networks (sn_id, user_id) values (10, 3);
insert into safety_networks (sn_id, user_id) values (3, 9);
insert into safety_networks (sn_id, user_id) values (3, 7);
insert into safety_networks (sn_id, user_id) values (3, 5);
insert into safety_networks (sn_id, user_id) values (3, 2);
insert into safety_networks (sn_id, user_id) values (3, 1);
insert into safety_networks (sn_id, user_id) values (3, 4);
